# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//visibility:public"])

exports_files([
    "rules.bzl",
    "extensions.bzl",
    "github_hugo_theme.bzl",
    "hugo_repository.bzl",
    "hugo_site.bzl",
    "hugo_site_autoprefixer.bzl",
    "hugo_site_brotli.bzl",
    "hugo_site_critical_css.bzl",
    "hugo_site_cssnano.bzl",
    "hugo_site_files.bzl",
    "hugo_site_info.bzl",
    "hugo_site_link_checker.bzl",
    "hugo_site_minify.sh",
    "hugo_site_minify.bzl",
    "hugo_site_optimize_images.bzl",
    "hugo_site_postcss.bzl",
    "hugo_site_purgecss.bzl",
    "hugo_site_prerender.bzl",
    "hugo_site_stylelint.bzl",
    "hugo_theme.bzl",
])