---
# Cirrus CI - Additional coverage alongside GitHub Actions
build_task:
  container:
    image: l.gcr.io/google/bazel:8.1.1
  setup_script:
    - apt-get update && apt-get install -y nodejs npm
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
  build_and_test_script:
    - bazel version
    - bazel build //hugo/...
    - bazel build //site_simple:site_simple //site_simple:site_simple_minified //site_simple:site_simple_br
    - bazel test //site_simple:site_test
    - bazel test //test_integration/minify:test_minify
    - bazel test //test_integration/brotli:test_brotli
    - bazel test //test_integration/critical_css:test_critical_css
